#ifndef MODULES_DEFS_H
# define MODULES_DEFS_H

# include "defs.h"

enum modules_error_code {
    MODULES_ERROR_CODE_START,
    MODULES_ERROR_CODE_SMTHIN_WENT_WRONG = 1,
    MODULES_ERROR_CODE_IDK_WHAT_HAPPENED = 2,
    MODULES_ERROR_CODE_SHOULD_FIX = 3,
    MODULES_ERROR_CODE_MANN = 4,
    MODULES_ERROR_CODE_INPUT_NOT_CORRECT = 5,
};

#endif
