#ifndef MODULES_DEFS_H
# define MODULES_DEFS_H

# include "defs.h"

enum modules_error_code {
    MODULES_ERROR_CODE_START,
    MODULES_ERROR_CODE_CONFIG_KEY_TOO_LONG = 0,
    MODULES_ERROR_CODE_UNIQUE_ERROR_CODE_KEY_TOO_LONG = 1,
    MODULES_ERROR_CODE_UNIQUE_ERROR_CODE_VALUE_TOO_LONG = 2,
    MODULES_ERROR_CODE_DEPENDENCY_MODULE_TOO_LONG = 3,
    MODULES_ERROR_CODE_DEPENDENCY_NOT_FOUND = 4,
    MODULES_ERROR_CODE_CONFIG_KEY_UNKNOWN = 5,
    MODULES_ERROR_CODE_CHILD_PREFIX_TOO_LONG = 6,
    MODULES_ERROR_CODE_ERROR_CODES_FILE_OPEN_FAIL = 7,
    MODULES_ERROR_CODE_UNEXPECTED_EOF_REACHED_ERROR_CODES = 8,
    MODULES_ERROR_CODE_LINE_BUFFER_SIZE_TOO_SMALL_ERROR_CODES = 9,
    MODULES_ERROR_CODE_VSSCANF_FAILED_TO_PARSE_LINE_ERROR_CODES = 10,
    MODULES_ERROR_CODE_BUFFER_SIZE_TOO_SMALL_ERROR_CODES = 11,
    MODULES_ERROR_CODE_DID_NOT_FIND_ERROR_CODE = 12,
    MODULES_ERROR_CODE_FORMAT_STRING_BUFFER_TOO_SMALL = 13,
};

#endif
