# CFLAGS_COMMON	:= -O2 -std=c11 -g -pedantic-errors -Wall -Wextra -Werror -I$(PATH_MODULES)
CFLAGS_COMMON	:= -std=c11 -g -pedantic-errors -Wall -Wextra -Werror -I$(PATH_MODULES)
LFLAGS_COMMON	:=

GIL_BUILD_MODE  := GIL_BUILD_MODE_DEBUG

ifeq ($(GIL_BUILD_MODE), GIL_BUILD_MODE_DEBUG)
CFLAGS_COMMON	+= -DGIL_DEBUG
else ifeq ($(GIL_BUILD_MODE), GIL_BUILD_MODE_RELEASE)
CFLAGS_COMMON 	+= -DGIL_RELEASE
endif

ifeq ($(PLATFORM), WINDOWS)
LFLAGS_COMMON += -lKernel32 -lm
endif

CFLAGS_COMMON += -DGIL_TEST_SHOULD_PRINT
