#ifndef PROCESS_DEFS_H
# define PROCESS_DEFS_H

# include "../system_defs.h"

enum PROCESS_ERROR_CODE {
    PROCESS_ERROR_CODE_FATAL = ERROR_CODE_PROCESS,
    PROCESS_ERROR_CODE_FORCED_TO_TERMINATE,
    PROCESS_ERROR_CODE_TERMINATED_ABRUPTLY,
    PROCESS_ERROR_CODE_INVALID_INPUT_SIZE_PROCESS_CREATE,

    PROCESS_ERROR_CODE_WINDOWS,
    PROCESS_ERROR_CODE_LINUX,
    PROCESS_ERROR_CODE_MAC
};

#endif
