#ifndef GENERIC_ARRAY_DEFS_H
# define GENERIC_ARRAY_DEFS_H

# include "../data_structures_defs.h"

enum generic_array_error_code {
    GENERIC_ARRAY_ERROR_CODE_START,
    GENERIC_ARRAY_ERROR_CODE_SIZE_OF_ONE_ITEM_IS_ZERO_IN_CREATE = 16,
    GENERIC_ARRAY_ERROR_CODE_INDEX_OUT_OF_RANGE_IN_AT = 17,
    GENERIC_ARRAY_ERROR_CODE_UNDERFLOW_IN_POP = 18,
    GENERIC_ARRAY_ERROR_CODE_OVERFLOW_IN_PUSH = 19,
};

#endif
