#ifndef LINEAR_ALLOCATOR_DEFS_H
# define LINEAR_ALLOCATOR_DEFS_H

# include "../memory_defs.h"

enum linear_allocator_error_code {
    LINEAR_ALLOCATOR_ERROR_CODE_START,
    LINEAR_ALLOCATOR_ERROR_CODE_OVERFLOW_IN_PUSH = 34,
    LINEAR_ALLOCATOR_ERROR_CODE_UNDERFLOW_IN_POP = 35,
    LINEAR_ALLOCATOR_ERROR_CODE_ALIGNMENT_NOT_POW_OF_2 = 36,
    LINEAR_ALLOCATOR_ERROR_CODE_OVERFLOW_IN_PUSH_ALIGNED = 37,
    LINEAR_ALLOCATOR_ERROR_CODE_UNEXPECTED_MEMORY_ADDRESS_IN_POP = 38,
};

#endif
