#ifndef LINEAR_ALLOCATOR_DEFS_H
# define LINEAR_ALLOCATOR_DEFS_H

# include "../memory_defs.h"

enum linear_allocator_error_code {
    LINEAR_ALLOCATOR_ERROR_CODE_START,
    LINEAR_ALLOCATOR_ERROR_CODE_OVERFLOW_IN_PUSH = 38,
    LINEAR_ALLOCATOR_ERROR_CODE_UNDERFLOW_IN_POP = 39,
    LINEAR_ALLOCATOR_ERROR_CODE_ALIGNMENT_NOT_POW_OF_2 = 40,
    LINEAR_ALLOCATOR_ERROR_CODE_OVERFLOW_IN_PUSH_ALIGNED = 41,
    LINEAR_ALLOCATOR_ERROR_CODE_UNEXPECTED_MEMORY_ADDRESS_IN_POP = 42,
};

#endif
