#ifndef MODULE_COMPILER_DEFS_H
# define MODULE_COMPILER_DEFS_H

# include "../tools_defs.h"

enum MODULE_COMPILER_RROR_CODE {
    MODULE_COMPILER_ERROR_CODE_FATAL = ERROR_CODE_MODULE_COMPILER
};

#endif
