#ifndef MODULE_COMPILER_DEFS_H
# define MODULE_COMPILER_DEFS_H

# include "../tools_defs.h"

enum module_compiler_error_code {
    MODULE_COMPILER_ERROR_CODE_START,
    MODULE_COMPILER_ERROR_CODE_CONFIG_KEY_TOO_LONG = 7,
    MODULE_COMPILER_ERROR_CODE_UNIQUE_ERROR_CODE_KEY_TOO_LONG = 8,
    MODULE_COMPILER_ERROR_CODE_UNIQUE_ERROR_CODE_VALUE_TOO_LONG = 9,
    MODULE_COMPILER_ERROR_CODE_DEPENDENCY_MODULE_TOO_LONG = 10,
    MODULE_COMPILER_ERROR_CODE_DEPENDENCY_NOT_FOUND = 11,
    MODULE_COMPILER_ERROR_CODE_CONFIG_KEY_UNKNOWN = 12,
    MODULE_COMPILER_ERROR_CODE_CHILD_PREFIX_TOO_LONG = 13,
    MODULE_COMPILER_ERROR_CODE_ERROR_CODES_FILE_OPEN_FAIL = 14,
    MODULE_COMPILER_ERROR_CODE_UNEXPECTED_EOF_REACHED_ERROR_CODES = 15,
    MODULE_COMPILER_ERROR_CODE_LINE_BUFFER_SIZE_TOO_SMALL_ERROR_CODES = 16,
    MODULE_COMPILER_ERROR_CODE_VSSCANF_FAILED_TO_PARSE_LINE_ERROR_CODES = 17,
    MODULE_COMPILER_ERROR_CODE_BUFFER_SIZE_TOO_SMALL_ERROR_CODES = 18,
    MODULE_COMPILER_ERROR_CODE_DID_NOT_FIND_ERROR_CODE = 19,
    MODULE_COMPILER_ERROR_CODE_FORMAT_STRING_BUFFER_TOO_SMALL = 20,

};

#endif
