#ifndef STRING_REPLACER_DEFS_H
# define STRING_REPLACER_DEFS_H

# include "../string_defs.h"

enum string_replacer_error_code {
    STRING_REPLACER_ERROR_CODE_START,
    STRING_REPLACER_ERROR_CODE_REACHED_MAXIMUM_AMOUNT_OF_REPLACEMENTS = 54,
    STRING_REPLACER_ERROR_CODE_REACHED_MAXIMUM_WITH_BUFFER_SIZE = 55,
    STRING_REPLACER_ERROR_CODE_WHAT_POSITION_ALREADY_EXISTS = 56,
    STRING_REPLACER_ERROR_CODE_WHAT_STRADDLES_ANOTHER_WHAT = 57,
    STRING_REPLACER_ERROR_CODE_WHAT_POSITION_OUTSIDE_OF_ORIGINAL = 58,
};

#endif
