#ifndef DIRECTORY_DEFS_H
# define DIRECTORY_DEFS_H

# include "../io_defs.h"

enum DIRECTORY_ERROR_CODE {
    DIRECTORY_ERROR_CODE_FATAL = ERROR_CODE_DIRECTORY

    DIRECTORY_ERROR_CODE_WINDOWS,
    DIRECTORY_ERROR_CODE_LINUX = DIRECTORY_ERROR_CODE_WINDOWS + 1 * (DIRECTORY_ERROR_CODE_FATAL + ERROR_CODE_DISPOSITION - DIRECTORY_ERROR_CODE_WINDOWS) / 3,
    DIRECTORY_ERROR_CODE_MAC   = DIRECTORY_ERROR_CODE_WINDOWS + 2 * (DIRECTORY_ERROR_CODE_FATAL + ERROR_CODE_DISPOSITION - DIRECTORY_ERROR_CODE_WINDOWS) / 3
};

#endif
