#ifndef FILE_DEFS_H
# define FILE_DEFS_H

# include "../io_defs.h"

enum file_error_code {
    FILE_ERROR_CODE_START,
    FILE_ERROR_CODE_ACCESS_MODE_INVALID = 6,
    FILE_ERROR_CODE_CREATION_MODE_INVALID = 7,
    FILE_ERROR_CODE_WINDOWS_READ = 8,
    FILE_ERROR_CODE_WINDOWS_WRITE = 9,
    FILE_ERROR_CODE_WINDOWS_SEEK = 10,
    FILE_ERROR_CODE_WINDOWS_CLOSE = 11,
};

#endif
