#ifndef FILE_DEFS_H
# define FILE_DEFS_H

# include "../io_defs.h"

enum FILE_ERROR_CODE {
    FILE_ERROR_CODE_FATAL = ERROR_CODE_FILE,

    ERROR_CODE_FILE_READER,

    FILE_ERROR_CODE_OPEN_ACCESS_INVALID = ERROR_CODE_FILE_READER + 1 * (FILE_ERROR_CODE_FATAL + ERROR_CODE_DISPOSITION - ERROR_CODE_FILE_READER) / 2,
    FILE_ERROR_CODE_OPEN_CREATION_INVALID,

    FILE_ERROR_CODE_WINDOWS,
    FILE_ERROR_CODE_LINUX = FILE_ERROR_CODE_WINDOWS + 1 * (FILE_ERROR_CODE_FATAL + ERROR_CODE_DISPOSITION - FILE_ERROR_CODE_WINDOWS) / 3,
    FILE_ERROR_CODE_MAC   = FILE_ERROR_CODE_WINDOWS + 2 * (FILE_ERROR_CODE_FATAL + ERROR_CODE_DISPOSITION - FILE_ERROR_CODE_WINDOWS) / 3,
};

#endif
