#ifndef SYSTEM_PLATFORM_SPECIFIC_DEFS_H
# define SYSTEM_PLATFORM_SPECIFIC_DEFS_H

# include "../../system_defs.h"

enum SYSTEM_WINDOWS_ERROR_CODE {
    SYSTEM_WINDOWS_ERROR_CODE_QUERY_PERFORMANCE_FREQUENCY = ERROR_CODE_SYSTEM_WINDOWS,
    SYSTEM_WINDOWS_ERROR_CODE_QUERY_PERFORMANCE_COUNTER
};

#endif
