#ifndef SYSTEM_PLATFORM_SPECIFIC_DEFS_H
# define SYSTEM_PLATFORM_SPECIFIC_DEFS_H

# include "../../system_defs.h"

enum system_windows_error_code {
    WINDOWS_SYSTEM_ERROR_CODE_START,
    SYSTEM_ERROR_CODE_SYSTEM_WINDOWS_ERROR_CODE_QUERY_PERFORMANCE_FREQUENCY = 33,
};

#endif
