#ifndef C_TOKENIZER_H
# define C_TOKENIZER_H

# include "c_tokenizer_defs.h"

struct tokenizer;
struct token;

PUBLIC_API bool tokenizer__tokenize_c_source_code(struct tokenizer* tokenizer, const char* source);
PUBLIC_API const char* token__type_name_c(struct token* token);

// C-file tokenizer
enum c_token_type {
    C_TOKEN_TYPE_KEYWORD_AUTO,
    C_TOKEN_TYPE_KEYWORD_BREAK,
    C_TOKEN_TYPE_KEYWORD_CASE,
    C_TOKEN_TYPE_KEYWORD_CHAR,
    C_TOKEN_TYPE_KEYWORD_CONST,
    C_TOKEN_TYPE_KEYWORD_CONTINUE,
    C_TOKEN_TYPE_KEYWORD_DEFAULT,
    C_TOKEN_TYPE_KEYWORD_DO,
    C_TOKEN_TYPE_KEYWORD_DOUBLE,
    C_TOKEN_TYPE_KEYWORD_ELSE,
    C_TOKEN_TYPE_KEYWORD_ENUM,
    C_TOKEN_TYPE_KEYWORD_EXTERN,
    C_TOKEN_TYPE_KEYWORD_FLOAT,
    C_TOKEN_TYPE_KEYWORD_FOR,
    C_TOKEN_TYPE_KEYWORD_GOTO,
    C_TOKEN_TYPE_KEYWORD_IF,
    C_TOKEN_TYPE_KEYWORD_INT,
    C_TOKEN_TYPE_KEYWORD_LONG,
    C_TOKEN_TYPE_KEYWORD_REGISTER,
    C_TOKEN_TYPE_KEYWORD_RETURN,
    C_TOKEN_TYPE_KEYWORD_SHORT,
    C_TOKEN_TYPE_KEYWORD_SIGNED,
    C_TOKEN_TYPE_KEYWORD_SIZEOF,
    C_TOKEN_TYPE_KEYWORD_STATIC,
    C_TOKEN_TYPE_KEYWORD_STRUCT,
    C_TOKEN_TYPE_KEYWORD_SWITCH,
    C_TOKEN_TYPE_KEYWORD_TYPEDEF,
    C_TOKEN_TYPE_KEYWORD_UNION,
    C_TOKEN_TYPE_KEYWORD_UNSIGNED,
    C_TOKEN_TYPE_KEYWORD_VOID,
    C_TOKEN_TYPE_KEYWORD_VOLATILE,
    C_TOKEN_TYPE_KEYWORD_WHILE,

    C_TOKEN_TYPE_IDENTIFIER, // asd

    C_TOKEN_TYPE_CONSTANT_INTEGER, // 32, 32L, 32ULL
    C_TOKEN_TYPE_CONSTANT_FLOAT, // 23.4f, 234.12, .32, 6.022e23
    C_TOKEN_TYPE_CONSTANT_OCTAL, // 032
    C_TOKEN_TYPE_CONSTANT_HEXA, // 0x3
    C_TOKEN_TYPE_CONSTANT_CHARACTER, // 'a', '\n'
    C_TOKEN_TYPE_CONSTANT_STRING, // "asd"

    C_TOKEN_TYPE_OPERATOR_FUNCTION_POSTFIX_INCREMENT, // ++
    C_TOKEN_TYPE_OPERATOR_FUNCTION_POSTFIX_DECREMENT, // --
    C_TOKEN_TYPE_OPERATOR_MEMBER_SELECTOR_DOT, // .
    C_TOKEN_TYPE_OPERATOR_MEMBER_SELECTOR_ARROW, // ->
    C_TOKEN_TYPE_OPERATOR_PREFIX_INCREMENT, // ++
    C_TOKEN_TYPE_OPERATOR_PREFIX_DECREMENT, // --
    C_TOKEN_TYPE_OPERATOR_UNARY_PLUS, // +
    C_TOKEN_TYPE_OPERATOR_UNARY_MINUX, // -
    C_TOKEN_TYPE_OPERATOR_LOGICAL_NOT, // !
    C_TOKEN_TYPE_OPERATOR_BITWISE_NOT, // ~
    C_TOKEN_TYPE_OPERATOR_ADDRESS_OF, // 
    C_TOKEN_TYPE_OPERATOR_DIVISION, // /
    C_TOKEN_TYPE_OPERATOR_MODULO, // %
    C_TOKEN_TYPE_OPERATOR_BITWISE_LEFT_SHIFT, // <<
    C_TOKEN_TYPE_OPERATOR_BITWISE_RIGHT_SHIFT, // >>
    C_TOKEN_TYPE_OPERATOR_LESS_THAN, // <
    C_TOKEN_TYPE_OPERATOR_LESS_THAN_OR_EQUAL_TO, // <=
    C_TOKEN_TYPE_OPERATOR_GREATER_THAN, // >
    C_TOKEN_TYPE_OPERATOR_GREATER_THAN_OR_EQUAL_TO, // >=
    C_TOKEN_TYPE_OPERATOR_EQUAL_TO, // ==
    C_TOKEN_TYPE_OPERATOR_NOT_EQUAL_TO, // !=
    C_TOKEN_TYPE_OPERATOR_BITWISE_XOR, // ^
    C_TOKEN_TYPE_OPERATOR_BITWISE_OR, // |
    C_TOKEN_TYPE_OPERATOR_LOGICAL_AND, // &&
    C_TOKEN_TYPE_OPERATOR_LOGICAL_OR, // ||
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_DIRECT, // =
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_SUM, // +=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_DIFFERENCE, // -=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_PRODUCT, // *=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_QUOTIENT, // /=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_REMAINDER, // %=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_BITWISE_LEFT_SHIFT, // <<=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_BITWISE_RIGHT_SHIFT, // >>=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_BITWISE_AND, // &=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_BITWISE_XOR, // ^=
    C_TOKEN_TYPE_OPERATOR_ASSIGNMENT_BY_BITWISE_OR, // |=
    C_TOKEN_TYPE_OPERATOR_COMMA, // ,

    C_TOKEN_TYPE_SPECIAL_CHARACTER_SEMICOLON, // ;
    C_TOKEN_TYPE_SPECIAL_CHARACTER_COLON, // :
    C_TOKEN_TYPE_SPECIAL_CHARACTER_QUESTION_MARK, // ?
    C_TOKEN_TYPE_SPECIAL_CHARACTER_APOSTROPHE, // \'
    C_TOKEN_TYPE_SPECIAL_CHARACTER_DOUBLE_QUOTATION_MARK, // "
    C_TOKEN_TYPE_SPECIAL_CHARACTER_BACKWARD_SLASH,
    C_TOKEN_TYPE_SPECIAL_CHARACTER_OPENING_CURLY_BRACKET, // {
    C_TOKEN_TYPE_SPECIAL_CHARACTER_CLOSING_CURLY_BRACKET, // }
    C_TOKEN_TYPE_SPECIAL_CHARACTER_LEFT_BRACKET, // [
    C_TOKEN_TYPE_SPECIAL_CHARACTER_RIGHT_BRACKET, // ]
    C_TOKEN_TYPE_SPECIAL_CHARACTER_LEFT_PARAM, // (
    C_TOKEN_TYPE_SPECIAL_CHARACTER_RIGHT_PARAM, // )
    C_TOKEN_TYPE_SPECIAL_CHARACTER_AMPERSAND, // &
    C_TOKEN_TYPE_SPECIAL_CHARACTER_HASH_SIGN, // #
    C_TOKEN_TYPE_SPECIAL_STAR, // *

    C_TOKEN_TYPE_COMMENT, // either in between /**/ or after // till end of line

    C_TOKEN_TYPE_PREPROCESSOR_DEFINE, //#define <text>
    C_TOKEN_TYPE_PREPROCESSOR_INCLUDE, //#include <text>
    C_TOKEN_TYPE_PREPROCESSOR_INCLUDE_NEXT, //#include_next <text>
    C_TOKEN_TYPE_PREPROCESSOR_IF, //#if <text>
    C_TOKEN_TYPE_PREPROCESSOR_ELIF, //#elif
    C_TOKEN_TYPE_PREPROCESSOR_ELSE, //#else
    C_TOKEN_TYPE_PREPROCESSOR_ENDIF, //#endif
    C_TOKEN_TYPE_PREPROCESSOR_IFDEF, //#ifdef <text>
    C_TOKEN_TYPE_PREPROCESSOR_IFNDEF, //#ifndef <text>
    C_TOKEN_TYPE_PREPROCESSOR_IFDEFINED, //#if defined(<text>)
    C_TOKEN_TYPE_PREPROCESSOR_UNDEF, //#undef <text>
    C_TOKEN_TYPE_PREPROCESSOR_PRAGMA, //#pragma <text>
    C_TOKEN_TYPE_PREPROCESSOR_PRAGMA_ONCE, //#pragma once
    C_TOKEN_TYPE_PREPROCESSOR_ERROR, //#error <text>
    C_TOKEN_TYPE_PREPROCESSOR_LINE, //#line <text>
};

#endif // C_TOKENIZER_H
