#ifndef PROCESS_PLATFORM_SPECIFIC_DEFS_H
# define PROCESS_PLATFORM_SPECIFIC_DEFS_H

# include "../../process_defs.h"

enum PROCESS_ERROR_CODE_WINDOWS {
    PROCESS_ERROR_CODE_WINDOWS_CLOSE_HANDLE = PROCESS_ERROR_CODE_WINDOWS,
    PROCESS_ERROR_CODE_WINDOWS_GET_EXIT_CODE_PROCESS,
    PROCESS_ERROR_CODE_WINDOWS_WAIT_FOR_SINGLE_OBJECT,
    PROCESS_ERROR_CODE_WINDOWS_WAIT_FOR_INPUT_IDLE_FAILED,
    PROCESS_ERROR_CODE_WINDOWS_GET_STD_HANDLE,
};

# include <Windows.h>

struct process {
    PROCESS_INFORMATION process_info;
};

#endif
